[versions]
# plugins
ktx-version = "1.9.0"
androidGradlePlugin-version = "8.0.2"

# libraries
junit-version = "4.13.2"
junitExt-version = "1.1.5"
mockitoCore-version = "4.8.0"
mockitoKotlin-version = "4.0.0"
coroutinesTest-version = "1.6.4"
espressoCore-version = "3.5.0"
appcompat-version = "1.5.1"
androidx-lifecycle-version = "2.4.0"
material-version = "1.7.0"
numberPicker-version = "2.4.13"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx-version" }

# Tests
junit = { module = "junit:junit", version.ref = "junit-version" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junitExt-version" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore-version" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin-version" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest-version" }
androidx-espresso-test = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore-version" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat-version" }
androidx-lifecycle-common =  { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "androidx-lifecycle-version" }
androidx-lifecycle-runtime =  { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-version" }
androidx-lifecycle-livedata =  { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle-version" }
androidx-lifecycle-viewmodel =  { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-version" }
material = { group = "com.google.android.material", name = "material", version.ref = "material-version" }
numberPicker = { group = "io.github.ShawnLin013", name = "number-picker", version.ref = "numberPicker-version" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin-version" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin-version" }

[bundles]
tests = [ "junit", "mockito-core", "mockito-kotlin", "kotlinx-coroutines-test" ]
androidTests = [ "junit-ext", "androidx-espresso-test" ]
lifecycle = ["androidx-lifecycle-common", "androidx-lifecycle-runtime", "androidx-lifecycle-livedata", "androidx-lifecycle-viewmodel"]