# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new relase candidate to internal tests"
  lane :internal do |options|
    package_name = options[:packageName]
    artifact = options[:artifact]

    upload_to_play_store(
      package_name: package_name,
      track: "internal",
      aab: artifact
    )
  end

  desc "Deploy a new version to production"
  lane :production do |options|
    package_name = options[:packageName]
    artifact = options[:artifact]

    upload_to_play_store(
      package_name: package_name,
      track: "production",
      aab: artifact
    )
  end
end
