name: "Build All Targets"

on:
  workflow_dispatch:
  push:
    # tags:
    #   - '[0-9]+.[0-9]+.[0-9]+'
    # branches:
    #   - release/*

jobs:  
  build_n_deploy_all:
    strategy:
      matrix: 
        target: [mobile, wear]

    uses: ./.github/workflows/build_n_deploy.yml
    with:
      target: ${{ matrix.target }}
    secrets: inherit