name: Android CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '19'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest jacocoTestReport

    - name: Test Report
      uses: dorny/test-reporter@v1      
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: JUnit Tests
        path: core/build/test-results/testDebugUnitTest/**/TEST-*.xml
        reporter: 'java-junit'

    - name: Publish Coverage to Codecov
      uses: codecov/codecov-action@v3
      if: success()