name: Reusable build variant release workflow

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  deploy:
    name: 'Release for ${{ inputs.target }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - uses: actions/download-artifact@v3
        with: 
          name: ${{ inputs.target }}
          path: 'artifacts'
        
      - name: Create Google Play Config file
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
        run : |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
      
      - name: Distribute app to Internal Testing track 🚀
        run: |
          bundle exec fastlane internal_${{inputs.target}} \
            artifact:$(find . -iname "*.aab") \
            packageName:dev.lucianosantos.intervaltimer